### ISSUE TITLE
add icons

### ISSUE THREAD

**Issue by annecori** [mrc-ide/typochallenge#30]
suggest adding following icons:
- when date is correctly entered: https://fontawesome.com/icons/check?style=solid next to "Last entry was correct" 
- when date is incorrectly entered: https://fontawesome.com/icons/times?style=solid next to "Typo in previous entry" 
- https://fontawesome.com/icons/user-cog?style=solid next to "Your statistics"
- https://fontawesome.com/icons/users-cog?style=solid next to "All time statistics"

**Comment by annecori** [comment]
Also, not sure if feasible, but could use this icon
https://fontawesome.com/icons/trophy?style=solid
to celebrate achievements (10/50/100/500 entries or correct entries or sth like that?)
Ideally we would want to write on top or near the icon the threshold number. Not sure if feasible but putting this here as a dream wishlist :-) Let's see what you think @richfitz!

**Comment by annecori** [comment]
@richfitz thanks for that - looks cool! does that mean my second request (just above this) is not feasible?

**Comment by richfitz** [comment]
Not infeasible, just didn't get time to get it done on the train!
