### ISSUE TITLE
ask emails of participant if they want to know more about the study

### ISSUE THREAD

**Issue by annecori** [mrc-ide/typochallenge#41]

**Comment by annecori** [comment]
idea is to store emails in a different text file on secure server, with no way to link with other data
(store by alphabetical order)

**Comment by richfitz** [comment]
If you're happy with the text here @annecori, this is implemented now and can be closed

**Comment by annecori** [comment]
just waiting to hear from Maria about GDPR statement we surely need to add there...

**Comment by richfitz** [comment]
I moved that into a separate issue as #56
