### ISSUE TITLE
add acknowledgement section

### ISSUE THREAD

**Issue by annecori** [mrc-ide/typochallenge#52]

**Comment by annecori** [comment]
mrc funding/hackout/recon
hpru funding
rich
maria
public
Imperial College / PHE / LSHTM?

**Comment by annecori** [comment]
not clear where this should go - perhaps easier on the main website
could also add Rob

**Comment by richfitz** [comment]
Is this not going to happen @annecori ?

**Comment by annecori** [comment]
I will do that early next week
