### ISSUE TITLE
PLACEHOLDER for website address

### ISSUE THREAD

**Issue by annecori** [mrc-ide/typochallenge#54]
`PLACEHOLDER` needs to be replaced with the website address in 
- consent.html
- doc_end.html
- footer.html

**Comment by richfitz** [comment]
do you want the share buttons going to the app or the main website? currently they (will) go to the app

**Comment by annecori** [comment]
@MJomaba what do you think? I am thinking the website but not sure...

**Comment by richfitz** [comment]
Do we have an address yet @annecori ?

**Comment by annecori** [comment]
nope - waiting for JS to send me one
